---
- name: install nut client
  yum:
    name: "{{nut_client_package }}"
    enablerepo: epel
    state: latest

- name: configure upsmon.conf
  template:
    src: upsmon.conf.j2
    dest: "{{ nut_config_path }}/upsmon.conf"
    owner: root
    group: "{{ nut_user }}"
    mode: 0640
  notify:
    - restart nut-monitor
